### PR TITLE
Support sqlite engine.

### PR DESCRIPTION
**Pull request by lbolla**
Factored out the code that converts DB types back to Go types, as it is
DB dependent. Issue #6.

### CODE REVIEW

**Comment by eaigner** [comment]
Nice! Although the dialect probably should not be registered by default since the driver has compile prerequisites (and it doesn't seem to compile on my system at all).

**Comment by eaigner** [comment]
Anyway, thanks! I'll merge it in asap.

**Comment by lbolla** [comment]
That's a good point. Another thing that might be useful to change is to have separate packages for different dialects (pg/, sqlite/) instead of flat .go files living in the same "hood" package: this would avoid name clashes (as in the _test.go files).

**Comment by eaigner** [comment]
Will try to get this resolved first https://github.com/mattn/go-sqlite3/issues/32 before merging (can't test if I cannot compile the driver)

**Comment by eaigner** [comment]
Managed to work around the issue and compile the `sqlite3` dylib with `i386` and `x86_84`

**Pull request merged**
