### PR TITLE
Removed Index Type, and move the functionality to tag.

### PR DESCRIPTION
**Pull request by coocood**
The tag's syntax is like
`sql:"index(.;*/other_column1/other_column2)"`
`sql:"index(*)"`
where "." or "_" is the alias of current field's snake name, "." means normal index, "_" means unique index.
"/" is used to separate column names.
";" is used to separate indexes.

### CODE REVIEW

**Comment by eaigner** [comment]
Sorry, but I won't pull this.
- A field tag is logically associated with a column, not a table. An index is a property that operates on a table, hence the field. If the language would support tags on whole structs, that would be OK, but it doesn't. Defining an index in a tag makes no sense logically, and if it means that someone has to type `json:"-"` on an index field, I'm fine with that. Not everything has to be optimized to be minimal syntax, if the language just doesn't support options to do that in a way that makes sense.
- The syntax is even more weird than the one proposed earlier

**Comment by coocood** [comment]
If a column is deleted all index contains that column will be deleted too, and if a column name is change, all associated index will be changed accordingly. 
So an index is practically associated with a column.
Bind the index to a column makes more sense than make it independent.

If you don't like the syntax I can changed it to the way you like. Please reconsider it.

**Comment by eaigner** [comment]
I skimmed through the code, and it doesn't seem that the index is deleted/changed automatically if the column is dropped/changed, making it even more difficult to maintain.

**Comment by eaigner** [comment]
PS: I'm not saying I reject the idea, it just seems half-baked to me at the moment. I'll keep this pull request open.

**Comment by coocood** [comment]
Dropping the index is the database's work, not the application code's.
At least in MySQL, I'm not sure how other database works.

**Comment by eaigner** [comment]
Another proposal: we keep the index fields, but make them anonymous. This should also resolve the json "problem".

**Comment by coocood** [comment]
you can't have multiple anonymous field with the same type.
unless you define multiple index in one tag, then you would end up with the "weird" syntax.

**Comment by coocood** [comment]
a field is a property of a row, you make the index a property of a row because you think it is the property of a table.

**Comment by eaigner** [comment]
Right, anonymous fields would be limited to one... bad idea. Scrap that.

**Comment by eaigner** [comment]
> a field is a property of a row, you make the index a property of a row because you think it is the property of a table.

A multi column index is damn sure no property of a SINGLE column, thus belongs to the table.

**Comment by eaigner** [comment]
I'm closing this again, this leads to nothing (unless Go would provide tags for the entire struct, which it doesn't).

**Comment by coocood** [comment]
All right, for me this problem is meaningless, because I almost never use mulit column index, so we agree to differ.

**Comment by eaigner** [comment]
Yes, but unfortunately as the root repository I have to keep everybody's needs in mind :). That's what forks are for.

**Pull request closed without merging**
